export type Link = { label: string; href: string };
export type FooterGroup = { title: string; links: Link[] };
export type SiteSettings = {
  brandName: string;
  logoPath: string;
  darkLogoPath?: string;
  iconPath: string;
  tagline: string;
  footerIntro: string;
  address: string;
  email: string;
  phoneDisplay: string;
  phoneE164: string;
  whatsappPhone: string;
  whatsappGreeting: string;
  whatsappSubtitle: string;
  headerCtaLabel: string;
  headerCtaHref: string;
  navLinks: Link[];
  serviceLinks: Link[];
  footerGroups: FooterGroup[];
};
export type Page = {
  _id?: string;
  slug: string;
  title: string;
  description: string;
  bodyClass: string;
  html: string;
  published: boolean;
  updatedAt?: string;
};
export type Programme = {
  name: string;
  level: string;
  field: string;
  tuition?: number | null;
  currency: string;
  duration: string;
  intake: string;
  requirements: string;
};
export type University = {
  _id?: string;
  slug: string;
  name: string;
  type: 'Public' | 'Private' | 'Other';
  city: string;
  country: string;
  website: string;
  logoUrl: string;
  description: string;
  levels: string[];
  fields: string[];
  tuitionFrom?: number | null;
  tuitionCurrency: string;
  tuitionNote: string;
  intakes: string;
  entryRequirements: string;
  programmes: Programme[];
  verifiedAt: string | null;
  published: boolean;
  updatedAt?: string;
};
export type Inquiry = {
  _id: string;
  name: string;
  email: string;
  organisation: string;
  subject: string;
  message: string;
  universitySlug: string;
  status: 'new' | 'in-progress' | 'closed';
  createdAt: string;
};
export type AdminUser = { id?: string; _id?: string; fullName?: string; email: string; role: 'owner' | 'editor'; active?: boolean };
